name = "LatticeProteins"
uuid = "2b3394db-9f9c-454f-a26a-0ad872321417"
authors = "Jorge Fernandez-de-Cossio-Diaz <j.cossio.diaz@gmail.com>"
version = "1.0.1-DEV"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.9"
DelimitedFiles = "1"
LogExpFunctions = "0.3"